name: Tiveron
markdown: redcarpet
pygments: true

# Personal Details
name:		Tiveron
author:     Thiago Tiveron Favaro
email:		thiagotf9@gmail.com
github:		http://github.com/tiveron
linkedin:	http://linkedin.com/in/tiveron/
twitter:	http://twitter.com/tiveron
instagram:	"@tiveron"